# Generated by Django 5.2.3 on 2025-06-27 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='Evidencija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('pleat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplication.plate')),
            ],
        ),
    ]
